version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: jennieines
      POSTGRES_PASSWORD: 343270
      POSTGRES_DB: itemscanner
    ports:
      - "5432:5432"

  nodeapp:
    build:
      context: ./server
    ports:
      - "3001:3001"
    depends_on:
      - postgres
